### ISSUE TITLE
does it still work in 2024

### ISSUE THREAD

**Issue by david-m-w** [danielholmes/coc-base-analyser#3]

**Comment by danielholmes** [comment]
@david-m-w The README talks about a game connection. I had one that was working for a little while when I first created this project, but Supercell constantly change how the game communicates with their servers and the one I was using stopped being supported. If you can find a new game connection then it may work, but my guess is it will take a few code tweaks as well since the game has changed since then (which buildings are possible for which town hall level and the like)
